# ==========================================
# CONFIGURAÇÃO DO BANCO DE DADOS (SUPABASE)
# ==========================================

# URL limpa, parando logo depois de /postgres
spring.datasource.url=jdbc:postgresql://db.raykwpryvxfittrlkbey.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=NataGestao73

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE / SPRING DATA
# ==========================================

# Faz o Java criar e atualizar as tabelas no Supabase automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL sendo executados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Informa que estamos usando o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=natasistema120@gmail.com
spring.mail.password=netm mqvr cjpq zxsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true